// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: {
    'Tutorial': [{type: 'autogenerated', dirName: 'slurm-cluster/tutorial'}], 
    'Service': [{type: 'autogenerated', dirName: 'slurm-cluster/services'}], 
    'System': [{type: 'autogenerated', dirName: 'slurm-cluster/system'}],
    'Containerisation': [{type: 'autogenerated', dirName: 'containerisation'}]
  },
  researchSidebar: {'Research': [{type: 'autogenerated', dirName: 'research'}]},

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
